Removing to minicom. removes timer adds loop first go

diff --git a/scripts/build_modem_status b/scripts/build_modem_status
--- a/scripts/build_modem_status
+++ b/scripts/build_modem_status
@@ -1,15 +1,17 @@
 #!/bin/bash
 
-# First Generate Data
-/usrdata/simpleadmin/scripts/get_modem_data.py 
-if [ $? -eq 0 ] 
-then 
-    # Parse
-    if [ -f /tmp/modemstatus.txt ]
+while true; do
+    # Your loop logic here
+    echo -en "AT+QSPN;+CEREG=2;+CEREG?;+CEREG=0;+C5GREG=2;+C5GREG?;+C5GREG=0;+CSQ;+QENG=\"servingcell\";+QRSRP;+QCAINFO;+QNWPREFCFG=\"mode_pref\";+QTEMP\r\n" | microcom -t 5000 /dev/ttyOUT > /tmp/modemstaus.txt
+    if [ $? -eq 0 ]
     then
-	/usrdata/simpleadmin/scripts/modemstatus_parse.sh
+        # Parse
+        if [ -f /tmp/modemstatus.txt ]
+        then
+    	/usrdata/simpleadmin/scripts/modemstatus_parse.sh
+        fi
+    else
+        # echo "Failed to Run Script"
     fi
-else
-    echo "Failed to Run Script"
-    exit 1
-fi
+    sleep 30  # Add a sleep to avoid CPU overload
+done
